spring:
  application:
    name: agenda-aulas
  profiles:
    active: local

jwt:
  secret: ${JWT_SECRET:troque-esse-segredo-antes-de-ir-pra-producao-precisa-ter-32-bytes}
  expiration-ms: 86400000 # 24 horas

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:file:./data/agendaaulas
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
